name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      apply:
        description: 'Executar o Terraform apply'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false

permissions:
  id-token: write
  contents: read

jobs: 
  job1: 
    name: Terraform
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::339855175962:role/GitHubinfraRole
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Debug - listar arquivos
        run: ls -R

      - name: Terraform Init
        run: terraform init
        working-directory: fase-3-docker-aws-terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: fase-3-docker-aws-terraform
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: fase-3-docker-aws-terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: fase-3-docker-aws-terraform
        if: github.event.inputs.apply == 'true'